# Generated by Django 5.1.15 on 2026-04-18 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chapters',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('theory_content', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.chapter')),
            ],
            options={
                'db_table': 'lessons',
                'ordering': ('chapter__order', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('starter_code', models.TextField(blank=True)),
                ('solution_query', models.TextField()),
                ('expected_result', models.JSONField(default=dict)),
                ('is_chapter_quiz', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='curriculum.chapter')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='curriculum.lesson')),
            ],
            options={
                'db_table': 'exercises',
                'ordering': ('chapter__order', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ExerciseHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint_text', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='curriculum.exercise')),
            ],
            options={
                'db_table': 'exercise_hints',
                'ordering': ('exercise_id', 'order'),
                'constraints': [models.UniqueConstraint(fields=('exercise', 'order'), name='hint_unique_order_per_exercise')],
            },
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('chapter', 'order'), name='lesson_unique_order_in_chapter'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['lesson', 'order'], name='exercises_lesson__7e8b69_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['chapter', 'is_chapter_quiz'], name='exercises_chapter_49adc0_idx'),
        ),
    ]
