# Generated by Django 5.1.15 on 2026-04-18 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SandboxSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('schema_sql', models.TextField(help_text='DDL + INSERT statements that set up this dataset.')),
                ('is_playground', models.BooleanField(default=False, help_text='Used by the free-play sandbox page when true.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sandbox_schemas',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ExerciseDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='curriculum.exercise')),
                ('sandbox_schema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercise_datasets', to='sandbox.sandboxschema')),
            ],
            options={
                'db_table': 'exercise_datasets',
                'constraints': [models.UniqueConstraint(fields=('exercise', 'sandbox_schema'), name='dataset_unique_per_exercise_schema')],
            },
        ),
    ]
